# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'kafka-broker'
    static_configs:
    - targets: ['kafka1.example.com:7075','kafka2.example.com:7075','kafka3.example.com:7075']

  - job_name: 'kafka_exporter'
    static_configs:
    - targets: ['kafka1.example.com:9308']

  - job_name: 'zookeeper'
    static_configs:
    - targets: ['zookeeper1.example.com:7075','zookeeper1.example.com:7075','zookeeper1.example.com:7075']
